Update pull-check.yml

diff --git a/.github/workflows/pull-check.yml b/.github/workflows/pull-check.yml
--- a/.github/workflows/pull-check.yml
+++ b/.github/workflows/pull-check.yml
@@ -15,18 +15,34 @@ jobs:
         with:
           repository: 'Checkmarx/ast-cli'
 
+      - name: Set up Go environment
+        uses: actions/setup-go@v4
+        with:
+          go-version: 1.20 # ใส่เวอร์ชัน Go ที่เหมาะสมกับโปรเจกต์ของคุณ
+
+      - name: Build cx binary
+        run: |
+          export GOARCH=amd64
+          export GOOS=linux
+          go build -o ./bin/cx ./cmd
+        env:
+          GOPATH: ${{ github.workspace }}/go
+
+      - name: Verify cx binary
+        run: |
+          if [ ! -f "./bin/cx" ]; then
+            echo "Error: cx binary not created!"
+            exit 1
+          else
+            echo "cx binary created successfully."
+            ls -lh ./bin/cx
+          fi
+
       - name: Set up QEMU 🏗️
         uses: docker/setup-qemu-action@v3.2.0
 
       - name: Set up Docker Buildx 🐋
         uses: docker/setup-buildx-action@v3.7.1
-
-      - name: Check file
-        run: |
-          echo "รายการไฟล์ทั้งหมด:"
-          ls -R .
-          echo "ค้นหาไฟล์ cx:"
-          find . -name "cx"
 
       - name: Login to JFrog 🐸  
         uses: docker/login-action@v3.3.0
